<?php
error_reporting(0);
class instagram {
	public function get($username) {
		$ch = curl_init();

		curl_setopt($ch, CURLOPT_URL, "https://i.instagram.com/api/v1/users/web_profile_info/?username={$username}");
		curl_setopt($ch, CURLOPT_RETURNTRANSFER, 1);
		curl_setopt($ch, CURLOPT_CUSTOMREQUEST, 'GET');

		curl_setopt($ch, CURLOPT_ENCODING, 'gzip, deflate');

		$headers = array();
		$headers[] = 'Authority: i.instagram.com';
		$headers[] = 'Accept: */*';
		$headers[] = 'Accept-Language: en-US,en;q=0.9';
		$headers[] = 'Origin: https://www.instagram.com';
		$headers[] = 'Referer: https://www.instagram.com/';
		$headers[] = 'Sec-Ch-Ua: ^^';
		$headers[] = 'Sec-Ch-Ua-Mobile: ?0';
		$headers[] = 'Sec-Ch-Ua-Platform: ^^Windows^^\"\"';
		$headers[] = 'Sec-Fetch-Dest: empty';
		$headers[] = 'Sec-Fetch-Mode: cors';
		$headers[] = 'Sec-Fetch-Site: same-site';
		$headers[] = 'User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/102.0.5005.63 Safari/537.36 Edg/102.0.1245.33';
		$headers[] = 'X-Asbd-Id: 198387';
		$headers[] = 'X-Csrftoken: 0';
		$headers[] = 'X-Ig-App-Id: 936619743392459';
		$headers[] = 'X-Ig-Www-Claim: 0';
		curl_setopt($ch, CURLOPT_HTTPHEADER, $headers);

		$result = curl_exec($ch);
		$result = json_decode($result, true);
		
		return $result;

		if (curl_errno($ch)) {
			echo 'Error:' . curl_error($ch);
		}
		curl_close($ch);
	}

	public function has_next_page($uid, $hash, $username) {
		// Generated by curl-to-PHP: http://incarnate.github.io/curl-to-php/
		$ch = curl_init();

		$param = json_encode([
			"id" => $uid,
			"first" => 12,
			"after" => $hash
		]);

		// {
		// 	"id":"13944481912",
		// 	"first":12,
		// 	"after":"QVFCaktKQVUySjBBNmdFSVk0dUJMMVY0azd4MDBuMTRrUXhnYVlFWVBoSGxmZ2hMWkJFamNnWUJaQjBmTmFycG1TcW5VeDFWcG5pUjdJYndQdEs5aVl0SQ=="
		// }

		curl_setopt($ch, CURLOPT_URL, "https://www.instagram.com/graphql/query/?query_hash=69cba40317214236af40e7efa697781d&variables={$param}");
		curl_setopt($ch, CURLOPT_RETURNTRANSFER, 1);
		curl_setopt($ch, CURLOPT_CUSTOMREQUEST, 'GET');

		curl_setopt($ch, CURLOPT_ENCODING, 'gzip, deflate');

		$headers = array();
		$headers[] = 'Authority: www.instagram.com';
		$headers[] = 'Accept: */*';
		$headers[] = 'Accept-Language: en-US,en;q=0.9';
		$headers[] = "Referer: https://www.instagram.com/${username}/";
		$headers[] = 'Sec-Ch-Prefers-Color-Scheme: dark';
		$headers[] = 'Sec-Ch-Ua: ^^';
		$headers[] = 'Sec-Ch-Ua-Mobile: ?0';
		$headers[] = 'Sec-Ch-Ua-Platform: ^^Windows^^\"\"';
		$headers[] = 'Sec-Fetch-Dest: empty';
		$headers[] = 'Sec-Fetch-Mode: cors';
		$headers[] = 'Sec-Fetch-Site: same-origin';
		$headers[] = 'User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/102.0.5005.63 Safari/537.36 Edg/102.0.1245.33';
		$headers[] = 'X-Asbd-Id: 198387';
		$headers[] = 'X-Csrftoken: 0';
		$headers[] = 'X-Ig-App-Id: 936619743392459';
		$headers[] = 'X-Ig-Www-Claim: 0';
		$headers[] = 'X-Requested-With: XMLHttpRequest';
		curl_setopt($ch, CURLOPT_HTTPHEADER, $headers);

		$result = curl_exec($ch);
		$result = json_decode($result, true);
		return $result;

		if (curl_errno($ch)) {
			echo 'Error:' . curl_error($ch);
		}
		curl_close($ch);
	}
}